version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: traffic-postgres
    restart: always
    environment:
      POSTGRES_DB: traffic_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"